[TOC]

# 响应处理和数据严重

## 1、响应类型

- 成功响应
- 错误响应

## 2、成功响应处理

-----

成功响应处理比较简单，正如前面规范提到的，根据不同情况返回对应状态码（200、201）和内容。

## 3、错误响应处理

-----

我们可以通过koa-controllers的同意错误处理函数来捕获错误，并同时输出。

```typescript
// file: backend/src/app.ts
// ...
await bootstrapControllers(app, {
        router,
        basePath: '/api',
        versions: [1],
        controllers: [
            path.resolve(__dirname, 'controllers/**/*')
        ],
        errorHandler: async(err: any, ctx: Context) => {
            let status = 500;
            let body: any = {
                statusCode: status,
                error: "Internal Server error",
                message: "An internal server error occurred"
            }
            ctx.status = status
            ctx.body = body
        }
    })
// ....
```



## 4、验证请求数据

----

许多时候，我们会对请求携带的数据进行一些必要的验证。

### 4.1、params

对于params数据，我们可以直接通过path规则进行验证。

```typescript
// file: backend/src/controllers/Test.ts
// .....
@Get('/user/:id(\\d+)')
    async getUser(
        // @Params() p: {id: number}
        @Params('id') id: number
    ) {
        return '当前parmas中id：' + id
    }
```

### 4.2、query和body

对于query和body数据，我们可以通过class-validator库进行统一处理。

#### 4.2.1、定义验证类

通过类来定义要验证的数据。其中，属性表示要验证的数据名称，配合着class-validator提交的装饰器来定义数据验证规则。

```typescript
import {IsNumberString} from 'class-validator'

class GetUsersQuery {
    @IsNumberString()
    page: number
}
```

#### 4.2.2、使用验证

把验证类作为要验证的参数（如：query）的类型。当请求该路由以后就会使用验证类对对应的数据进行验证。

```typescript
@Get('/users')
    async getUsers(
        @Query() q: GetUsersQuery
    ) {
        return '当前parmas中id：' + q.page
    }
```

## 5、其他业务逻辑错误

有些错误是一些业务逻辑等方面的错误，比如：用户已注册，没有该用户等。

这里会用到一个库@hapi/Boom，上面的class-validator与koa-ts-colntroller配合严重中，也是使用它。他提供一些api,返回对应HTTP状态相应格式。

```typescript
import Boom from '@hapi/Boom'
@Get('/users')
    async getUsers(
        @Query() q: GetUsersQuery
    ) {
        // 业务逻辑出现了错误，比如用户不存在，用户名已经被注册
        if (true) {
            throw Boom.notFound('注册失败', '用户名已被注册')
        }
        return '当前parmas中id：' + q.page
    }
```

## 6、路由错误

```typescript
// router.all('*', async ctx => {
    //     throw Boom.notFound('没有找到该路由')
    // })
```

app.ts中使用这个报错，暂未解决